- name: remove old service file
  file:
    dest: /etc/systemd/system/zabbix-agent.service
    state: absent

- name: remove old logfile
  file:
    dest: /var/log/zabbix-agent/zabbix-agent.log
    state: absent

- name: Install repos
  apt:
    deb: https://repo.zabbix.com/zabbix/4.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.2-1+bionic_all.deb

- name: Install agent
  apt:
    name: zabbix-agent

- name: Add config
  template:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix agent

- name: Zabbix agent started
  systemd:
    name: zabbix-agent
    enabled: true
    daemon_reload: true
    state: started

