postgres_user: walter
postgres_db: walter



# NGINX
nginx_remove_default_vhost: true
nginx_vhosts:
  - listen: "80"
    server_name: shortcurl.com
    extra_parameters: |
      location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }


