composes:
  - name: postgres
  - name: zabbix-agent

nginx_vhosts:
  - listen: "80"
    server_name: default
    extra_parameters: |
      location / {
        return 404;
      }
      location /nginx_status {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        deny all;
      }


  - listen: "80"
    server_name: shortcurl.com
    filename: "redirect.shortcurl.com"
    extra_parameters: |
      server_name _;
      return 301 https://$host$request_uri;

  - listen: "80"
    server_name: www.shortcurl.com
    filename: "redirect.www.shortcurl.com"
    extra_parameters: |
      server_name _;
      return 301 https://$host$request_uri;

  - listen: "443 ssl"
    server_name: "www.shortcurl.com"
    extra_parameters: |
      ssl_certificate /etc/letsencrypt/live/www.shortcurl.com/cert.pem;
      ssl_certificate_key /etc/letsencrypt/live/www.shortcurl.com/privkey.pem;
      location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

  - listen: "443 ssl"
    server_name: "shortcurl.com"
    extra_parameters: |
      ssl_certificate /etc/letsencrypt/live/shortcurl.com/cert.pem;
      ssl_certificate_key /etc/letsencrypt/live/shortcurl.com/privkey.pem;
      location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }



