
composes:
  - name: walter-listen
    image: banjocat/walter
    tag: walter
  - name: walter-sync
    image: banjocat/walter
    tag: walter
  - name: wesley
    image: banjocat/walter
    tag: wesley

timers:
  - name: walter-sync
    period: 5m



nginx_vhosts:
  - listen: "80"
    server_name: default
    extra_parameters: |
      location / {
        return 404;
      }

  - listen: "80"
    server_name: brief.pw
    filename: "redirect.shortcurl.com"
    extra_parameters: |
      server_name _;
      return 301 https://$host$request_uri;

  - listen: "443 ssl"
    server_name: brief.pw
    extra_parameters: |
      ssl_certificate /etc/letsencrypt/live/brief.pw/cert.pem;
      ssl_certificate_key /etc/letsencrypt/live/brief.pw/privkey.pem;
      location / {
        proxy_pass http://127.0.0.1:8002;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }




