# Generated by Django 2.2.2 on 2019-06-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('url', models.URLField()),
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'short_url',
            },
        ),
        migrations.AddConstraint(
            model_name='shorturl',
            constraint=models.UniqueConstraint(fields=('url',), name='unique_url'),
        ),
    ]
