# Generated by Django 2.2.2 on 2019-06-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.URLField(max_length=40000),
        ),
    ]
