- name: Make log dir
  file:
    path: /var/log/shortcurl
    state: directory

- name: login into docker
  docker_login:
    username: "{{ lookup('env', 'DOCKER_USER') }}"
    password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"

- include_tasks: compose.yml
  with_items: "{{ composes }}"
  loop_control:
    loop_var: compose

- include_tasks: timer.yml
  with_items: "{{ timers }}"
  loop_control:
    loop_var: timer
  tags: timer

- name: logout of docker
  docker_login:
    username: "{{ lookup('env', 'DOCKER_USER') }}"
    state: absent
