# Generated by Django 2.2.2 on 2019-06-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicShortURL',
            fields=[
                ('url', models.URLField()),
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='basicshorturl',
            constraint=models.UniqueConstraint(fields=('url',), name='unique_url'),
        ),
    ]
