# Generated by Django 2.2.2 on 2019-06-15 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20190615_0305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortURL',
            new_name='ShortA',
        ),
        migrations.AlterModelTable(
            name='shorta',
            table='short_url_a',
        ),
    ]
