# Generated by Django 2.2.2 on 2019-06-15 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_auto_20190615_0307'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shorta',
            table='short_a',
        ),
    ]
