- hosts: short
  gather_facts: yes
  vars:
    domain_email: jackmuratore@gmail.com
    domains:
      - brief.pw
  roles:
    - role: geerlingguy.nginx
      tags: nginx
    - role: banjocat_ansible/certbot_nginx
      tags: tls
    - role: redis
      tags: redis
    - role: compose
      tags: compose

