- hosts: data
  vars:
    domain_email: jackmuratore@gmail.com
    domains:
      - shortcurl.com
      - www.shortcurl.com
    composes:
      - name: walter-api
        image: banjocat/walter:walter
        tag: walter
      - name: zabbix-agent
  roles:
    - role: tls
      tags: tls
    - role: geerlingguy.nginx
      tags: nginx
    - role: compose
      tags: compose

