- hosts: jack
  vars:
    domain_email: jackmuratore@gmail.com
    domains:
      - jackmuratore.com
      - www.jackmuratore.com
      - monitor.jackmuratore.com
      - grafana.jackmuratore.com
  roles:
    - role: banjocat_ansible/certbot_nginx
      tags: tls
    - role: geerlingguy.nginx
      tags: nginx
    - role: compose
      tags: compose

