- hosts: jackmuratore
  vars:
    domain_email: jackmuratore@gmail.com
    domains:
      - jackmuratore.com
      - www.jackmuratore.com
      - monitor.jackmuratore.com
      - grafana.jackmuratore.com
  roles:
    - role: tls
      tags: tls
    - role: geerlingguy.nginx
      tags: nginx
    - role: compose
      tags: compose
    - role: zabbix_server
      tags: server

