version: '3'
services:
  walter-sync:
    image: banjocat/walter:walter
    network_mode: host
    environment:
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_HOST: "shortcurl.com"
      DJANGO_DEBUG: "no"
      SENTRY_DSN: "{{ walter_sync_sentry_dsn }}"
    command: python manage.py full_short_sync

