version: '3'
services:
  zabbix-agent:
    image: banjocat/zabbix-agent:latest
    network_mode: host
    privileged: true
    environment:
      ZBX_HOSTNAME: "{{ ansible_hostname }}"
      ZBX_SERVER_HOST: "{{ zabbix_server_host }}"
      ZBX_LISTENIP: "{{ ansible_default_ipv4.address }}"




