version: '3'
services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-4.0-latest
    network_mode: host
    environment:
      ZBX_HOSTNAME: "{{ ansible_hostname }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_DB: "zabbix"
      DB_SERVER_HOST: shortcurl.com
