version: '3'
services:
  zabbix-server:
    image: banjocat/zabbix-server:latest
    network_mode: host
    volumes:
      - /var/lib/zabbix:/var/lib/zabbix
      - /usr/lib/zabbix:/usr/lib/zabbix
    environment:
      ZBX_HOSTNAME: "{{ ansible_hostname }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_DB: "zabbix"
      DB_SERVER_HOST: shortcurl.com
