version: '3'
services:
  walter-api:
    image: banjocat/walter:walter
    network_mode: host
    environment:
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_HOST: "127.0.0.1"
      DJANGO_DEBUG: "no"
      SENTRY_DSN: "{{ walter_api_sentry_dsn }}"
    command: gunicorn walter.wsgi


